# Generated by Django 3.2.7 on 2021-09-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papers',
            fields=[
                ('PaperId', models.AutoField(primary_key=True, serialize=False)),
                ('PaperName', models.CharField(max_length=500)),
                ('DateOfCreated', models.DateField()),
                ('saved_file', models.FileField(upload_to='')),
            ],
        ),
    ]
