# Generated by Django 3.2.7 on 2021-09-21 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ownapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='papers',
            old_name='DateOfCreated',
            new_name='DateOfCreating',
        ),
    ]
