# Generated by Django 3.2.7 on 2021-09-22 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ownapp', '0002_rename_dateofcreated_papers_dateofcreating'),
    ]

    operations = [
        migrations.AddField(
            model_name='papers',
            name='Creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
